[project]
name = "multiagent-bmi-fastapi"
version = "0.1.0"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["mabmi"]

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[[tool.mypy.overrides]]
module = [".*", "pupil_labs.*", "aiortc.*", "gym", "av"]
ignore_missing_imports = true
