[project]
name = "multiagent-bmi-fastapi"
version = "0.1.0"
readme = "README.md"
dependencies = [
    # server
    "fastapi",
    "uvicorn",
    "aiortc",
    # client
    "websockets",
    "pupil-core-network-client",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["mabui"]

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.mypy]
disable_error_code = ["import-untyped"]
